/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "view_data.h"

typedef struct _uib_view1_control_context {
	/* add your variables here */

} uib_view1_control_context;

